### ISSUE TITLE
Could you please provide a detailed tutorial or documentation that can run the whole algorithm successfully?

### ISSUE THREAD

**Issue by yuuma002** [g4alllf/SASD#2]
Thank you for open-sourcing this remarkable project.

We are interested in building upon your work but have encountered some challenges while attempting to run the complete algorithm. The README.md file provides instructions for executing the `Distilling the Auxiliary Model` phase; however, it lacks guidance on how to perform `Fine-Tuning the Auxiliary Model` and `Weight Scaling` phases.

Could you please provide a detailed tutorial or documentation that can run the whole algorithm successfully?

Thank you very much.

**Comment by g4alllf** [comment]
Hi,

Thank you for your interest and support of our project. Below is the sample command to run finetuning:

```
python src/finetune.py \
    -m resnet50 \
    -e 1 \
    -o SAM \
    -b 20 \
    -l 0.05 \
    -w './results/raw_SAM_lr_0.05_models/'
```
Examples of weight scaling can be found in the project's evaluation code. You can also perform weight scaling by caling the _all_scale_ function from _src.utils.scale_weight_.

If you have any further questions, feel free to reach out.
